[project]
name = "mcp_progetto_meteo"
version = "0.1.0"
description = "Server MCP per consultare la temperatura di una città"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "mcp[cli]",
    "uvicorn",
    "httpx",
    "requests"
]